-- Zeal Tangerang — Supabase schema
-- Run this once in the Supabase SQL Editor (Project → SQL Editor → New query → paste → Run).
-- Safe to re-run from scratch on a brand new project; NOT idempotent against a partially-applied
-- previous run (drop the tables first if you need to re-apply after a failed partial run).
--
-- Ordering note: `members` must be created BEFORE `is_leader_or_admin()` because
-- it's a `language sql` function — unlike `plpgsql`, Postgres parses/validates
-- a `sql`-language function body against the catalog at CREATE FUNCTION time,
-- not lazily at first call. Every table is created (bare, no RLS yet) before
-- any function or policy that references it.

create extension if not exists pgcrypto;

-- ============================================================================
-- members
-- ============================================================================
create table public.members (
  id integer generated by default as identity primary key,
  name text not null,
  role text not null default 'member' check (role in ('super_admin', 'leader', 'member')),
  group_id text not null,
  status text check (status in ('Strong', 'Concern', 'Weak')),
  love_lang text,
  gender text check (gender in ('L', 'P')),
  bday date,
  spiritual_bday date,
  mentor_id integer references public.members(id),
  partner_id integer references public.members(id),
  phone text,
  service text[] not null default '{}',
  education jsonb,
  job jsonb,
  email text unique,
  auth_user_id uuid unique references auth.users(id),
  created_at timestamptz not null default now()
);

-- ============================================================================
-- invites
-- ============================================================================
create table public.invites (
  token text primary key default encode(gen_random_bytes(16), 'hex'),
  group_id text not null,
  invited_by integer not null references public.members(id),
  status text not null default 'pending' check (status in ('pending', 'used')),
  note text,
  created_at timestamptz not null default now(),
  used_at timestamptz,
  expires_at timestamptz
);

-- ============================================================================
-- activities  (Pertemuan: Ibadah Minggu / PDG / Bible Talk / Fellowship / Lainnya)
-- ============================================================================
create table public.activities (
  id integer generated by default as identity primary key,
  title text not null,
  type text not null check (type in ('Ibadah Minggu', 'PDG', 'Bible Talk', 'Fellowship', 'Lainnya')),
  date date not null,
  groups text[] not null default '{}',
  attendance jsonb not null default '{}',
  created_at timestamptz not null default now()
);

-- ============================================================================
-- bs_cases  (Bible Study) — sessions kept as a JSONB array on the parent row,
-- since sessions are always read/written together with their case; no
-- independent query pattern justifies a join table.
-- ============================================================================
create table public.bs_cases (
  id integer generated by default as identity primary key,
  person_name text not null,
  teacher_id integer references public.members(id),
  status text not null default 'Aktif' check (status in ('Aktif', 'Selesai')),
  sessions jsonb not null default '[]',
  created_at timestamptz not null default now()
);

-- ============================================================================
-- Helper: is the currently-authenticated caller a leader or super_admin?
-- security definer + explicit search_path so this can be used inside RLS
-- policies defined on the very table it queries, without recursing.
-- ============================================================================
create or replace function public.is_leader_or_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.members m
    where m.auth_user_id = auth.uid()
      and m.role in ('leader', 'super_admin')
  );
$$;

-- ============================================================================
-- members: RLS
-- ============================================================================
alter table public.members enable row level security;

create policy "members_select_authenticated" on public.members
  for select using (auth.uid() is not null);

create policy "members_insert_leader" on public.members
  for insert with check (public.is_leader_or_admin());

create policy "members_update_leader_or_self" on public.members
  for update using (public.is_leader_or_admin() or auth_user_id = auth.uid())
  with check (public.is_leader_or_admin() or auth_user_id = auth.uid());

create policy "members_delete_leader_or_admin" on public.members
  for delete using (public.is_leader_or_admin());

-- ============================================================================
-- invites: RLS
-- Deliberately NO policy grants `anon` any access at all. RLS-enabled-with-no-
-- matching-policy denies by default — the two RPC functions below are the ONLY
-- doors a logged-out invitee has into this table.
-- Tokens are hex-only (0-9a-f): the app's hash-router splits/replaces on '_' and
-- '/', so a base64url token (which uses exactly those two characters) would
-- silently corrupt the invite link. Do not change this to base64/base64url.
-- ============================================================================
alter table public.invites enable row level security;

create policy "invites_manage_leader" on public.invites
  for all using (public.is_leader_or_admin()) with check (public.is_leader_or_admin());

-- ============================================================================
-- activities: RLS
-- ============================================================================
alter table public.activities enable row level security;

create policy "activities_select_authenticated" on public.activities
  for select using (auth.uid() is not null);

create policy "activities_insert_leader" on public.activities
  for insert with check (public.is_leader_or_admin());

create policy "activities_update_leader" on public.activities
  for update using (public.is_leader_or_admin()) with check (public.is_leader_or_admin());

create policy "activities_delete_leader" on public.activities
  for delete using (public.is_leader_or_admin());

-- NOTE (v1 scope, documented not silently accepted): attendance-edit granularity in the UI
-- restricts a given cell to "super_admin, or the leader of THAT member's group" — a per-JSON-key
-- rule RLS can't express at the row level. v1 ships coarse: any leader/admin can update any
-- activity row. A `set_attendance(activity_id, member_id, status, reason)` security-definer RPC
-- checking per-group ownership is the documented follow-up if per-group precision matters later.

-- ============================================================================
-- bs_cases: RLS
-- Read+write restricted to leader/admin only: these are pastoral notes.
-- (BSDetail.jsx today has NO permission guard at all on editing them — this is
-- a real hardening over today's behavior, not a migrated regression.)
-- ============================================================================
alter table public.bs_cases enable row level security;

create policy "bs_select_leader" on public.bs_cases
  for select using (public.is_leader_or_admin());
create policy "bs_insert_leader" on public.bs_cases
  for insert with check (public.is_leader_or_admin());
create policy "bs_update_leader" on public.bs_cases
  for update using (public.is_leader_or_admin()) with check (public.is_leader_or_admin());
create policy "bs_delete_leader" on public.bs_cases
  for delete using (public.is_leader_or_admin());

-- ============================================================================
-- Invite redemption — the only two functions the public `anon` role can call
-- to touch `invites`/`members`. Both security definer, both re-validate state
-- inside the function body (never trust a prior lookup).
-- ============================================================================
create or replace function public.get_invite_by_token(p_token text)
returns table (group_id text, invited_by_name text, status text)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select i.group_id, m.name, i.status
  from public.invites i
  join public.members m on m.id = i.invited_by
  where i.token = p_token
    and i.status = 'pending'
    and (i.expires_at is null or i.expires_at > now());
$$;

grant execute on function public.get_invite_by_token(text) to anon, authenticated;

-- Registration always creates a real Supabase Auth account (email+password,
-- confirmed via emailed link, or Google OAuth) before this runs — so unlike a
-- typical "redeem invite" RPC, this one requires an authenticated caller and
-- links the new member row to that session's auth.uid() directly.
create or replace function public.finalize_registration(
  p_token text,
  p_phone text,
  p_gender text,
  p_bday date,
  p_spiritual_bday date
) returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_invite public.invites%rowtype;
  v_new_id integer;
  v_name text;
  v_email text;
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;

  if exists (select 1 from public.members where auth_user_id = v_uid) then
    raise exception 'already_registered';
  end if;

  -- row-lock so two simultaneous finalize calls for the same token can't both
  -- pass the pending check before either commits
  select * into v_invite from public.invites where token = p_token for update;

  if not found or v_invite.status <> 'pending'
     or (v_invite.expires_at is not null and v_invite.expires_at <= now()) then
    raise exception 'invite_invalid_or_used';
  end if;

  select email, coalesce(raw_user_meta_data->>'name', raw_user_meta_data->>'full_name', split_part(email, '@', 1))
    into v_email, v_name
  from auth.users where id = v_uid;

  insert into public.members (name, role, group_id, phone, gender, bday, spiritual_bday, mentor_id, status, auth_user_id, email)
  values (v_name, 'member', v_invite.group_id, p_phone, p_gender, p_bday, p_spiritual_bday, v_invite.invited_by, 'Strong', v_uid, v_email)
  returning id into v_new_id;

  update public.invites set status = 'used', used_at = now() where token = p_token;

  return v_new_id;
end;
$$;

grant execute on function public.finalize_registration(text, text, text, date, date) to authenticated;
